apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-8o0j
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qopr-tenant/rhtap-demo-app/hacbs-test-project-8o0j@sha256:016b33628394c7fa93e84a24e5a5111ba1ab1e843921c144b2c10f05193c864f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
